include_guard(GLOBAL)

function(dvc_add_papyrus_targets)
  add_custom_target(papyrus
    COMMAND "${CMAKE_COMMAND}"
      -DDVC_PAPYRUS_COMPILE:BOOL=$<BOOL:${DVC_PAPYRUS_COMPILE}>
      -DPAPYRUS_COMPILER:FILEPATH=${PAPYRUS_COMPILER}
      -DPAPYRUS_FLAGS_FILE:FILEPATH=${PAPYRUS_FLAGS_FILE}
      -DSKYRIM_PAPYRUS_SOURCE_DIR:PATH=${SKYRIM_PAPYRUS_SOURCE_DIR}
      -DSKYUI_PAPYRUS_SOURCE_DIR:PATH=${SKYUI_PAPYRUS_SOURCE_DIR}
      -DPAPYRUS_EXTRA_IMPORT_DIRS:STRING=${PAPYRUS_EXTRA_IMPORT_DIRS}
      -DDVC_PAPYRUS_SRC_DIR:PATH=${DVC_PAPYRUS_SRC_DIR}
      -DDVC_PAPYRUS_PEX_DIR:PATH=${DVC_PAPYRUS_PEX_DIR}
      -P "${CMAKE_SOURCE_DIR}/cmake/scripts/papyrus_compile.cmake"
    VERBATIM
  )
endfunction()
